
spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false # Enable service discovery for routing to other microservices based on Eureka registry
              lower-case-service-id: true
          httpclient:
            connect-timeout: 1000
            response-timeout: 2s
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "This microservice serves as the API gateway for routing requests to other microservices and handling cross-cutting concerns like authentication and rate limiting."
    version: "1.0.0"

logging:
  level:
    com:
      microservice:
        gatewayserver: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10 # How many requests required to change state from closed to open
        permitted-number-of-calls-in-half-open-state: 2 # How many requests allowed in half-open state before deciding to close or open again
        failureRateThreshold: 50 # Percentage of failed requests to trigger circuit breaker
        wait-duration-in-open-state: 10000 # Time in milliseconds to wait before transitioning from open to half-open state
